export const demoNames = [
  "button-variants",
  "button-sizes-demo",
  "input-demo",
  "input-states-demo",
  "input-sizes-demo",
  "input-types-demo",
  "checkbox-demo",
  "checkbox-states-demo",
  "dialog-demo",
  "tabs-demo",
  "table-demo",
  "data-table-demo",
  "header-demo",
  "burger-menu-demo",
  "sidebar-demo",
  "drawer-demo",
  "layouts-demo",
  "date-picker-demo",
  "map-marker-demo",
  "log-card-demo",
  "log-card-blocked-demo",
  "profile-card-demo",
  "rule-card-view-demo",
  "rule-card-edit-demo",
  "schedule-grid-demo",
  "sign-in-form-demo",
  "sign-in-form-errors-demo",
  "gallery-demo",
  "screen-mirror-demo",
  "event-timeline-demo",
  "app-shell-demo",
  "ai-chat-demo",
  "toggle-demo",
  "notifications-panel-demo",
  "toast-demo",
  "kpi-card-demo",
] as const;

export type DemoName = (typeof demoNames)[number];
